---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/aelsabbahy/dargs
    steps:
      - checkout
      - run: echo building
      - run: go get github.com/mitchellh/gox github.com/golang/dep/cmd/dep github.com/tcnksm/ghr
      - restore_cache:
          key: dargs-{{ checksum "Gopkg.toml" }}
      - run: dep ensure
        #- save_cache:
        #-   key: test_travis-{{ .Branch }}-{{ checksum "glide.lock" }}
        #-   paths:
        #-     - /go/src/github.com/aelsabbahy/test_travis/vendor
        #-     - /go/src/github.com/aelsabbahy/test_travis/.glide
      - run: ls /go/pkg/dep/sources
      - save_cache:
          key: dargs-{{ checksum "Gopkg.toml" }}
          paths:
            - /go/pkg/dep/sources
            - /go/src/github.com/aelsabbahy/dargs/vendor
      - run: gox -output 'release/dargs_{{.OS}}_{{.Arch}}' -osarch 'linux/amd64 darwin/amd64'
      # FIXME: Need to figure out workflows to get this to run only on tag pushes
      - run:
          name: Create draft release on GitHub
          command: |
            ghr -draft -u "$CIRCLE_PROJECT_USERNAME" "test-draft" release/
