---
version: 2
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/

defaults: &defaults
  docker:
    - image: circleci/golang:1.9
  working_directory: /go/src/github.com/aelsabbahy/dargs

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo building
      - run: go get github.com/mitchellh/gox github.com/golang/dep/cmd/dep
      - restore_cache:
          key: dargs-{{ checksum "Gopkg.toml" }}
      - run: dep ensure
      - run: ls /go/pkg/dep/sources
      - save_cache:
          key: dargs-{{ checksum "Gopkg.toml" }}
          paths:
            - /go/pkg/dep/sources
            - /go/src/github.com/aelsabbahy/dargs/vendor
      - run: gox -output 'release/dargs_{{.OS}}_{{.Arch}}' -osarch 'linux/amd64 darwin/amd64'
      - run: test/test.sh release/dargs_linux_amd64
      - persist_to_workspace:
          root: .
          paths:
            - release

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
        at: .
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Create draft release on GitHub
          command: |
            ghr -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" release/
